"""Added reconciliation models

Revision ID: 3b75423034d9
Revises: 034364041751
Create Date: 2026-03-07 10:53:50.081875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b75423034d9'
down_revision: Union[str, Sequence[str], None] = '034364041751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', name='reconciliationstatus'), server_default='PENDING', nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('listing_invoice_number', sa.String(), nullable=False),
    sa.Column('listing_vendor_name', sa.String(), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=False),
    sa.Column('listing_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('listing_tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('matched_invoice_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UNMATCHED', 'MATCHED', 'AMOUNT_MISMATCH', 'VENDOR_MISMATCH', 'DATE_MISMATCH', 'MISSING', name='result'), server_default='MISSING', nullable=False),
    sa.Column('discrepancies', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['reconciliation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_items')
    op.drop_table('reconciliation_sessions')
    # ### end Alembic commands ###
